/* =========================================================
   SimLab — Content & Configuration
   AUTO-GENERATED from Website_Journey_Content.xlsx
   Do NOT edit this file directly. Edit the spreadsheet and
   re-run:  python build_varfile.py <xlsx> varFile.js
========================================================= */

const siteSpecific = {
  title: "WCER SimLab — University of Wisconsin–Madison",
  tagline: "Simulation-Based Learning to Manage Challenging Situations",
  searchPlaceholder: "Ask anything about SimLab…",
  exploreLabel: "Explore",
  footer: "© 2025–2026 University of Wisconsin–Madison · Wisconsin Center for Education Research",
  menuItems: ["About", "Design", "Challenge", "Team", "Publications", "News", "Connect"],
  topLevel: ["Home"],
};

const contentItems = {
  About: {
    label: "About",
    context: "Mission, approach, and background",
    tags: ["About"],
  },
  Home: {
    label: "Home",
    context: "Select a topic above to explore SimLab concepts.",
    tags: ["Home"],
  },
  Design: {
    label: "Design",
    context: "Methods for development and delivery",
    tags: ["Design"],
  },
  Challenge: {
    label: "Challenge",
    context: "SimLab tackles challenging situations",
    tags: ["Challenge"],
  },
  Connect: {
    label: "Connect",
    context: "Ways to connect and collaborate",
    tags: ["Connect"],
  },
  Team: {
    label: "Team",
    context: "SimLab personnel",
    tags: ["Team"],
  },
  Publications: {
    label: "Publications",
    context: "SimLab publications and related scholarly work",
    tags: ["Publications"],
  },
  News: {
    label: "News",
    context: "News, events, and updates",
    tags: ["News"],
  },
  Hubal: {
    label: "Hubal",
    context: "SimLab's director",
    tags: ["Hubal"],
  },
  Partners: {
    label: "Partners",
    context: "SimLab's partners",
    tags: ["Partners"],
  },
  Engineering: {
    label: "Engineering",
    context: "Partnership in engineering",
    tags: ["Engineering"],
  },
  Ethics: {
    label: "Ethics",
    context: "Ethics as content",
    tags: ["Ethics"],
  },
  Nursing: {
    label: "Nursing",
    context: "Partnership in nursing",
    tags: ["Nursing"],
  },
  DifficultSkill: {
    label: "Difficult Skill",
    context: "Challenge: Practicing a difficult skill",
    tags: ["DifficultSkill"],
  },
  FraughtContent: {
    label: "Fraught Content",
    context: "Challenge: Handling fraught content",
    tags: ["FraughtContent"],
  },
  ChargedContext: {
    label: "Charged Context",
    context: "Challenge: Managing a charged context",
    tags: ["ChargedContext"],
  },
  AboutSimLab: {
    title: "About SimLab",
    text: "SimLab is a project within WCER established to address training and assessment of professionals' skills in managing challenging situations.",
    tags: ["About", "Home"],
  },
  SimLabMission: {
    title: "SimLab's Mission",
    text: "SimLab's mission is to provide practitioners with realistic, structured simulation experiences.",
    tags: ["About"],
  },
  SimLabApproach: {
    title: "SimLab's Approach",
    text: "SimLab uses modern assessment design, AI, and evidence-based professional learning approaches.",
    tags: ["Design"],
  },
  WhatIsChallenging: {
    title: "What Do We Mean by \"Challenging\"?",
    text: "SimLab tackles challenging situations involving difficult <a href=\"#\" data-nav=\"ChallengingTask\">tasks</a>, charged <a href=\"#\" data-nav=\"ChallengingContent\">content</a>, and stressful <a href=\"#\" data-nav=\"ChallengingContext\">contexts</a>.",
    tags: ["Design", "Challenge"],
  },
  ChallengingTask: {
    title: "What Are Challenging Tasks?",
    text: "The skill is difficult: A professional must demonstrate competence that is tough to acquire. Examples include giving hard feedback, being honest without damaging trust or motivation, or reading group dynamics and sensing tension, exclusion, confusion, or disengagement before it becomes problematic.",
    tags: ["Design", "Challenge", "DifficultSkill"],
  },
  ChallengingContent: {
    title: "What Is Challenging Content?",
    text: "The content is fraught: A professional must address a sensitive or nuanced topic. Examples include asking about one's or someone else's mental health, or feeling out a suspicion of worrying situations such as abuse.",
    tags: ["Design", "Challenge", "FraughtContent"],
  },
  ChallengingContext: {
    title: "What Are Challenging Contexts?",
    text: "The context is charged: A professional must defuse a potentially explosive situation. Examples include calming an angry individual or soothing a distraught individual, who may be at a peer level or at a higher or lower level in the social hierarchy.",
    tags: ["Design", "Challenge", "ChargedContext"],
  },
  SimLabOffers: {
    title: "What SimLab Offers",
    text: "SimLab offers professionals the opportunity to rehearse high-stakes conversations.",
    tags: ["About", "Home", "Design"],
  },
  ConnectWithUs: {
    title: "Connect With Us",
    text: "See our <a href=\"#\" data-nav=\"Team\">Team</a> page or email simlab@wcer.wisc.edu.",
    tags: ["Connect"],
  },
  PartnerSupport: {
    title: "Partner Support",
    text: "SimLab supports partners with simulation development, delivery, and analysis.",
    tags: ["Design", "Connect"],
  },
  SimLabDirector: {
    title: "SimLab's Director",
    text: "Dr. Hubal is a computational social scientist, with research interests that focus on the intelligence use of technology to better train and assess complex knowledge and skills. For over 25 years he has applied these interests toward simulations.",
    tags: ["About", "Team", "Hubal"],
  },
  AboutEngineeringWork: {
    title: "SimLab's Partnership In Engineering",
    text: "SimLab is working with colleagues in the UW–Madison School of Engineering on several projects including ethics simulations.",
    tags: ["Partners", "Engineering", "Ethics", "DifficultSkill", "FraughtContent"],
  },
  AboutNursingWork: {
    title: "SimLab's Partnership In Nursing",
    text: "SimLab is working with colleagues in the UW–Madison School of Nursing on several projects including improving clinical trials recruiting and end-of-life discussion simulations.",
    tags: ["About", "Partners", "Nursing", "DifficultSkill", "FraughtContent", "ChargedContext"],
  },
  AboutICTRWork: {
    title: "SimLab's Partnership with ICTR",
    text: "SimLab is working with colleagues in the UW–Madison ICTR on a project providing practice opportinties for perspectve seeking skills.",
    tags: ["About", "Partners", "Engineering", "DifficultSkill", "FraughtContent", "ChargedContext"],
  },
  AboutMMSDWork: {
    title: "SimLab's Partnership With MMSD",
    text: "SimLab is working with leaders in the Madison Metropolitan School District (MMSD) on a project providing practice opportinties for principals.",
    tags: ["About", "Partners", "Engineering", "DifficultSkill", "FraughtContent", "ChargedContext"],
  },
};

const keywordMap = {
  about: "About",
  mission: "About",
  design: "Design",
  method: "Design",
  methods: "Design",
  ai: "Design",
  simulation: "Design",
  simulations: "Design",
  challenge: "Challenge",
  challenging: "Challenge",
  skill: "DifficultSkill",
  task: "DifficultSkill",
  content: "FraughtContent",
  fraught: "FraughtContent",
  context: "ChargedContext",
  charged: "ChargedContext",
  team: "Team",
  people: "Team",
  staff: "Team",
  hubal: "Hubal",
  director: "Hubal",
  publications: "Publications",
  research: "Publications",
  news: "News",
  events: "News",
  connect: "Connect",
  contact: "Connect",
  email: "Connect",
  partner: "Connect",
  partnership: "Connect",
  engineering: "Engineering",
  nursing: "Nursing",
  ethics: "Ethics",
};